version: '3.1'
services:
  postgres:
    image: "postgres:9.6-alpine"
    container_name: pay-my-bills-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb